### ISSUE TITLE
Integrating randomgen components with Cython code

### ISSUE THREAD

**Issue by sseyler** [bashtage/randomgen#23]
I've been able to use randomgen successfully with my Cython-based project, though I had a decent amount of trouble getting proper object/pointer cleanup working. Part of this is due to my lack of familiarity with PyCapsules, which are used in the examples, and working with the pointer it provides.

Before I get too far into the weeds, I was curious about any thoughts on creating *.pxd definition files for each of the RNG classes for the purpose of being able to `cimport` the extension types directly into external Cython code. Is there a good reason for avoiding this approach and using PyCapsules instead?

I should mention that I was drawn to randomgen in large part because it grants access to disparate, state-of-the-art RNGs with the possibility of using them in parallel applications (e.g. using `nogil` functions in `parallel`/`prange` blocks in Cython).

**Comment by bashtage** [comment]
Providing a full pxd is probably hard since the BasicRNG needs some setup when it is instantized (either with entropy or with a seed), which means that it needs to be a Python object with a managed lifecycle.   My main motivation for providing some method to call functions using a low-level interface is to provide a continuum where code that can't be made fast enough in NumPy can be accelerated using one of the available routes.  It was also done to improve numba compatibility which uses its own generator AFAICT. 

One option would be to see it if it is feasible to cdef the low-level generators so that these could be exposed in Cython.  The BasicRNG will still need to be instantized in Python (or in Cython as a Python object)

**Comment by sseyler** [comment]
Thanks for the input. I'm going to put a little thought into this and see whether it makes sense (for me, at least) to cdef the generators.

**Comment by sseyler** [comment]
Quick question: I've written code that relies on RandomGen and the results will be published in a journal (probably Physical Review or similar); how would you prefer that I give proper attribution to your work?

P.S. I've made some changes to my own version of the package, but nothing that warrants a pull request yet (though possibly in the future). If I do end up doing something that I think is useful for the package, I'll post back here.

**Comment by bashtage** [comment]
I'll make a zenodo for the next release.  This will provide a simple method to cite this package.

**Comment by bashtage** [comment]
I'm going to close this since the citation point is available.
