### ISSUE TITLE
Please document source and meaning of constant 11400714819323198485ULL

### ISSUE THREAD

**Issue by garfi303** [bashtage/randomgen#249]
We very much appreciate your rapid turn-around on the bugfix to rdrand.

However, in reviewing the code, we have discovered that the constant `11400714819323198485ULL` is hardcoded. We cannot determine the source of this constant or its purpose.

https://github.com/bashtage/randomgen/blob/8c240461603b94a002c88d1214722bc00932387e/randomgen/src/rdrand/rdrand.h#L64

For our evaluation of this code, we need to be able to document the source of magic numbers such as this. 

Also, it seems that you are not checking the carry flag, but are instead relying on the fact that RDRAND returns all 0s when it fails.

Finally, we believe that this should generate a Python exception when it is run on platforms that do not implement RDRAND, as is the case with other RDRAND implementations, rather than simply returning 0. That is your choice, but it is not a fail safe condition, so we will need to document that as well.

Thanks again for your maintenance of this program.

**Comment by bashtage** [comment]
That number, when divided by 2**64, is the closes odd approximation to phi - 1 (the golden ratio - 1). This number doesn't matter and is only present to ensure that a rejection sampler will always be able to exit since this sequence is just a basic not very good random number generator.  However, it will also never be seen since it will raise RuntimeError whenever it is used.  

> Also, it seems that you are not checking the carry flag, but are instead relying on the fact that RDRAND returns all 0s when it fails.

I am: 

https://github.com/bashtage/randomgen/blob/6c98b41dcbdb1b8cf99ddb65f85827993bbda8f7/randomgen/rdrand.pyx#L37-L47

Here you see that if status is 0, after filling the buffer, which happens if RDRAND fails, then a RuntimeError is "raised". It isn't actually raised since it isn't possible to raise and stop execution inside code that has released the GIL, even if it reacquires the GIL.  This is why 

https://github.com/bashtage/randomgen/blob/6c98b41dcbdb1b8cf99ddb65f85827993bbda8f7/randomgen/rdrand.pyx#L58-L99

was introduced.  This lock, which is always used in NumPy's generator each time that random values are used, will clear the error code if any, and then check for an error.  if one occurred it will raise.  This is how the RuntimeError is actually raised. 



> Finally, we believe that this should generate a Python exception when it is run on platforms that do not implement RDRAND, as is the case with other RDRAND implementations, rather than simply returning 0. That is your choice, but it is not a fail safe condition, so we will need to document that as well.

It will always raise RuntimeError when RDRAND isn't supported.  This includes old x86 hardware and other platforms such as S390x, PPC and ARM which are all supported.

https://github.com/bashtage/randomgen/blob/6c98b41dcbdb1b8cf99ddb65f85827993bbda8f7/randomgen/rdrand.pyx#L225-L231

In the `__init__` you see that `rdrand_capable` is called which returns 0 on any platform that doesn't support RDRAND.  Hence you cannot ever generate a random value using RDRAND on these platforms. The 0 is returned since the `rdrand.pyx` has to compile any any platform whether RDRAND is available or not.  I could have chosen any value here since it will never be seen.

**Comment by bashtage** [comment]
The way to simulate a failure is documented in the class docstring.

```
import numpy as np
from randomgen import RDRAND

rd = RDRAND()
gen = np.random.Generator(rd)
gen.integers(0,10)
state = rd.state
state["retries"]=-1
rd.state = state
# raises RuntimeError
gen.integers(0,10,size=500)  # needs to exhaust the buffer which has valid values
```

**Comment by simsong** [comment]
That's the failure when it runs out of random numbers. There's another failure when the platform doesn't support RDRAND.

**Comment by bashtage** [comment]
> There's another failure when the platform doesn't support RDRAND.

If the platform doesn't support RDRAND then you will get a RuntimeError in the following code:

```
from randomgen import RDRAND
rd = RDRAND()  # raises: RuntimeError
```

This one cannot be simulated since the function `rdrand_capable` check the CPU feature flags for RDRAND support. If the CPU doesn't support it (e.g., old x86) or cannot support it (ARM, PPC, S390x) then this function returns 0 and the error is raised.  

Is this your question/issue, or is it something else?

**Comment by garfi303** [comment]
Ah, that's great. Thanks. Should we document the magic number?

**Comment by bashtage** [comment]
I've added some additional explanation in the code.
