### ISSUE TITLE
Performance differences with Julia?

### ISSUE THREAD

**Issue by paugier** [bashtage/randomgen#38]
Thank you very much for randomgen. It saves Python for fast random number generation!

Random number generation in Julia (https://docs.julialang.org/en/v1/stdlib/Random/index.html) with dSFMT (http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/SFMT/#dSFMT) seems to be super fast, i.e. more than 2 times faster than with randomgen.

Anyway, do you understand how Julia can be so fast with dSFMT?

With Julia 1.0.2:
```
julia> using BenchmarkTools

julia> @btime rand(UInt32, 1000000);
  820.706 μs (2 allocations: 3.81 MiB)

julia> @btime rand(1000000);
  1.400 ms (2 allocations: 7.63 MiB)
```

With randomgen (recompiled locally):
```
In [1]: from randomgen import RandomGenerator, DSFMT

In [2]: rnd = RandomGenerator()

In [3]: %timeit rnd.random_uintegers(1000000, bits=32)
2.71 ms ± 2.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [4]: %timeit rnd.rand(1000000)
3.88 ms ± 4.02 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [5]: rnd = RandomGenerator(DSFMT())

In [6]: %timeit rnd.random_uintegers(1000000, bits=32)
3.73 ms ± 6.52 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [7]: %timeit rnd.rand(1000000)
3.84 ms ± 6.57 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by bashtage** [comment]
I would guess that Julia is capable of inlining where useful.  The method used in randomgen to abstract the core random generator prevents inlining since the generator is passed around as a function pointer, and so there might be function overhead.  The only way to know for sure would be to step through the call using a debugger (or to otherwise look at the relevant assembly).

Function like `rand` do memory allocation and call even more functions, which all add time. 

This said, factor of 2 or 3 at the lower level isn't much, and certainly isn't worth optimization effort since most people are interested in more complex distributions.

**Comment by paugier** [comment]
Thank you for the explanations and once again for this library. Since there is nothing more to do, I close this "issue".
